CREATE INDEX CNameIndex ON CUSTOMERS (CNAME);
CREATE INDEX ENAMEIndex ON SALESPERSONS (ENAME);
CREATE INDEX SALESDATEIndex ON ORDERS (SALESDATE);
CREATE INDEX PARTIDIndex ON ORDERITEMS (PARTID);
CREATE INDEX DESCRIPTIONIndex ON INVENTORY (DESCRIPTION);