INSERT INTO CUSTOMERS
  SELECT * FROM C##SALESDB.CUSTOMERS;

INSERT INTO SALESPERSONS
 SELECT * FROM C##SALESDB.SALESPERSONS;

INSERT INTO INVENTORY
 SELECT * FROM C##SALESDB.INVENTORY;

INSERT INTO ORDERS
 SELECT * FROM C##SALESDB.ORDERS;

INSERT INTO ORDERITEMS
 SELECT * FROM C##SALESDB.ORDERITEMS;