CREATE TABLE CUSTOMERS
(CUSTID    NUMBER(4,0) PRIMARY KEY,
 CNAME CHAR(25),
 CREDIT   CHAR(1)    CHECK ( CREDIT IN ('A','B','C') ) NOT NULL);

CREATE TABLE SALESPERSONS
(EMPID    NUMBER(4,0) PRIMARY KEY NOT NULL,
 ENAME CHAR(15 BYTE),
 RANK  NUMBER(2,0)    CHECK (RANK IN (1,2,3) ),
 SALARY  NUMBER(8,2)     DEFAULT 1000 CHECK ( SALARY >= 1000 ));
 
CREATE TABLE INVENTORY 
(PARTID    NUMBER(4,0) PRIMARY KEY,
 DESCRIPTION CHAR(12 BYTE),
 STOCKQTY    NUMBER(4,0),
 REORDERPNT  NUMBER(4,0),
 PRICE NUMBER(8,2));

CREATE TABLE ORDERS 
(ORDERID    NUMBER(4,0) PRIMARY KEY NOT NULL,
 EMPID      NUMBER(4,0),
 CUSTID     NUMBER(4,0),
 CONSTRAINT FK_SALESPERSONS FOREIGN KEY (EMPID) REFERENCES SALESPERSONS,
 CONSTRAINT FK_CUSTOMERS    FOREIGN KEY (CUSTID) REFERENCES CUSTOMERS,
 SALESDATE  DATE);
  
CREATE TABLE ORDERITEMS
(ORDERID    NUMBER(4) NOT NULL,
 DETAIL     NUMBER(4),
 PARTID     NUMBER(4),
 QTY        NUMBER(6),
 CONSTRAINT PK_ORDERS PRIMARY KEY(ORDERID,DETAIL),
 CONSTRAINT FK_ORDERS FOREIGN KEY(ORDERID) REFERENCES ORDERS,
 CONSTRAINT FK_INVENTORY FOREIGN KEY(PARTID) REFERENCES INVENTORY
 );
 
